import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "drizzle/**",
      "next-env.d.ts", // generated by next build
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // The tenancy boundary from .cursor/rules/010-tenancy.mdc, enforced by the
    // linter rather than by memory.
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/db/client", "**/server/db/client", "@/server/db/client"],
              message:
                "Only src/server/repo/ may import the Drizzle client. Add or use a repository function that takes clinicId.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["src/server/repo/**", "src/server/db/**"],
    rules: { "no-restricted-imports": "off" },
  },
];

export default config;
