import { randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

/**
 * Password hashing for the single operator credential.
 *
 * scrypt is in Node, so there is no native addon to fail on Alpine. The stored
 * form is `scrypt:<salt>:<key>`, all base64url, generated by
 * `npm run hash-password`.
 */

const KEYLEN = 32;
const SCRYPT_COST = { N: 16384, r: 8, p: 1 } as const;

export function hashPassword(password: string, salt = randomBytes(16)): string {
  const key = scryptSync(password, salt, KEYLEN, SCRYPT_COST);
  return `scrypt:${salt.toString("base64url")}:${key.toString("base64url")}`;
}

export function verifyPassword(password: string, stored: string): boolean {
  const parts = stored.split(":");
  if (parts.length !== 3 || parts[0] !== "scrypt") return false;

  let salt: Buffer;
  let expected: Buffer;
  try {
    salt = Buffer.from(parts[1], "base64url");
    expected = Buffer.from(parts[2], "base64url");
  } catch {
    return false;
  }

  if (salt.length === 0 || expected.length === 0) return false;

  const actual = scryptSync(password, salt, expected.length, SCRYPT_COST);
  if (actual.length !== expected.length) return false;
  return timingSafeEqual(actual, expected);
}
